# **Data Types in Python**


In [1]:
# Python is dynamically typed, meaning you don't need to declare variable types explicitly.
# The interpreter infers the type at runtime.

# Example in Python:
x = 10  # x is an integer
x = "Hello"  # x is now a string


# In contrast, C is statically typed, requiring type declarations.

# Example in C:
# int x = 10; // x is declared as an integer
# x = "Hello"; // This would result in a compilation error

In [ ]:
# Integer
integer_variable = 10
print(type(integer_variable))  # Output: <class 'int'>

<class 'int'>


In [ ]:
# String
string_with_single_quotes = 'Hello, world!'
string_with_double_quotes = "Hello, world!"
string_with_apostrophe = "It's a beautiful day."

print(string_with_single_quotes)
print(string_with_double_quotes)
print(string_with_apostrophe)

# Different ways to print in Python

# 1. Using the print() function with a string literal
print("Welcome to SRH Campus Hamburg!")

# 2. Using f-strings (formatted string literals)
message = "Welcome to SRH"
print(f"{message}")

# 3. Using the % operator (older style formatting)
message = "Welcome to SRH Campus Hamburg!"
print("Message: %s" % message)

# 4. Using the str.format() method
message = "Welcome to SRH Campus Hamburg!"
print("{}".format(message))

# String methods such as replace, endswith methods on any string variable (Independent Reading)!

: 

In [ ]:
# Boolean
boolean_variable = True
print(type(boolean_variable))  # Output: <class 'bool'>

<class 'bool'>


In [ ]:
# List
list_variable = [1, 2, 3, "a", "b", "c"]
print(type(list_variable))  # Output: <class 'list'>
print(len(list_variable)) # Output: 6

# Generate a list using range function
my_list = list(range(10))

# Check the type of the list
print(type(my_list))  # Output: <class 'list'>
# Check the type of the elements in the list (first element as an example)
if my_list:
  print(type(my_list[0]))  # Output: <class 'int'>


# List comprehension
L = [1, 2, 3, 4, 5]

# List comprehension to create a new list with each element squared
L2 = [elem**2 for elem in L]

for elem in L:
  elem**2   # mind the indentiation in Python!!!

print(L2)  # Output: [1, 4, 9, 16, 25]

# List comprehension with condition (only include even numbers)
L3 = [x for x in L if x % 2 == 0]

print(L3)  # Output: [2, 4]


# enumerate method (try it out independent)

<class 'list'>
6
<class 'list'>
<class 'int'>
[1, 4, 9, 16, 25]
[2, 4]


In [ ]:
# Tuple

# A tuple is an ordered, immutable collection of elements.
# Immutable means that once a tuple is created, you cannot change its contents.

tuple_variable = (1, 2, 3, "a", "b", "c") # terms: () parentheses, [] brackets, {} curely brackets
print(type(tuple_variable))  # Output: <class 'tuple'>

# Accessing elements
print(tuple_variable[0])  # Output: 1
print(tuple_variable[3])  # Output: "a"

# Tuple Concatenation
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
new_tuple = tuple1 + tuple2
print(new_tuple)  # Output: (1, 2, 3, 4, 5, 6)

# Tuple Repetition
tuple3 = (1, 2)
repeated_tuple = tuple3 * 3
print(repeated_tuple)  # Output: (1, 2, 1, 2, 1, 2)

# Tuple Length
print(len(tuple_variable))  # Output: 6

# Check for element existence
print(1 in tuple_variable)  # Output: True
print(4 in tuple_variable)  # Output: False

# Tuple Unpacking
tuple_variable = (1, 2, 3, "a", 'a', "b", "c")
a, b, *c = tuple_variable
print(a)  # Output: 1
print(b)  # Output: 2
print(c)  # Output: [3, 'a', 'b', 'c']

# Tuple Methods
# Tuples have limited methods compared to lists because they are immutable.
# count() : counts the occurrences of an element
print(tuple_variable.count("a"))  # Output: 1       ************************
# index() : returns the index of the first occurrence of an element
print(tuple_variable.index("b"))  # Output: 4

<class 'tuple'>
1
a
(1, 2, 3, 4, 5, 6)
(1, 2, 1, 2, 1, 2)
6
True
False
1
2
[3, 'a', 'b', 'c']
1
4


In [ ]:
# Dictionary
dictionary_variable = {
                        "name": "Markus Doe",
                        "age": 30,
                        "city": "Hamburg"
                      }

print(type(dictionary_variable))  # Output: <class 'dict'>

# Accessing values using keys
print(dictionary_variable["name"])  # Output: John Doe
print(dictionary_variable["age"])   # Output: 30

# Getting all keys
print(dictionary_variable.keys())  # Output: dict_keys(['name', 'age', 'city'])
print(dictionary_variable.keys())

# Getting all values
print(dictionary_variable.values())  # Output: dict_values(['John Doe', 30, 'New York'])

# Getting all key-value pairs as tuples
print(dictionary_variable.items())  # Output: dict_items([('name', 'John Doe'), ('age', 30), ('city', 'New York')])

# Adding a new key-value pair
dictionary_variable["occupation"] = "Software Engineer"
print(dictionary_variable)

# Modifying an existing value
dictionary_variable["age"] = 45
print(dictionary_variable)

# Unpacking using individual key-value pairs:
name, age, city = dictionary_variable['name'], dictionary_variable['age'], dictionary_variable['city']
print(name, age, city)

# Unpacking only certain keys
new_dict = {**dictionary_variable, 'country': 'Germany'} # Merges values from my_dict into new_dict, add country: Germany
print(new_dict)

# Nested dictionary unpacking
my_nested_dict = {'user': {'name': 'Jane', 'age': 25}, 'address': {'city': 'London'}}

user_name, user_age = my_nested_dict['user'].values()
print(user_name, user_age) # Output: Jane 25

# Removing a key-value pair
del dictionary_variable["city"]
dictionary_variable

# Looping through a dictionary without list comprehension
my_dict = {'a': 1, 'b': 2, 'c': 3}

for key, value in my_dict.items():
  print(f"Key: {key}, Value: {value}")

# Looping through a dictionary with list comprehension
# Create a list of values
values = [value for key, value in my_dict.items()]
print(values)


# Creating a dictionary from Tuple
my_tuple = (('name', 'Markus Doe'), ('age', 30), ('city', 'Hamburg'))
my_dict = dict(my_tuple)
my_dict

<class 'dict'>
Markus Doe
30
dict_keys(['name', 'age', 'city'])
dict_values(['Markus Doe', 30, 'Hamburg'])
dict_items([('name', 'Markus Doe'), ('age', 30), ('city', 'Hamburg')])
{'name': 'Markus Doe', 'age': 30, 'city': 'Hamburg', 'occupation': 'Software Engineer'}
{'name': 'Markus Doe', 'age': 31, 'city': 'Hamburg', 'occupation': 'Software Engineer'}
Markus Doe 31 Hamburg
{'name': 'Markus Doe', 'age': 31, 'city': 'Hamburg', 'occupation': 'Software Engineer', 'country': 'Germany'}
Jane 25
Key: a, Value: 1
Key: b, Value: 2
Key: c, Value: 3
[1, 2, 3]


{'name': 'Markus Doe', 'age': 30, 'city': 'Hamburg'}

In [ ]:
# Set
# A set is an unordered collection of unique elements.
# It means that a set can't contain duplicate elements.
# Sets are useful for tasks like removing duplicates from a list or checking for membership in a collection.

# Creating a set:
my_set = {1, 2, 3, 4, 5}
print(my_set)  # Output: {1, 2, 3, 4, 5}

# Adding elements to a set:
my_set.add(6)
print(my_set) # Output: {1, 2, 3, 4, 5, 6}

# Removing elements from a set:
my_set.remove(3)
print(my_set) # Output: {1, 2, 4, 5, 6}

# Set operations:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Union (combines elements from both sets):
union_set = set1.union(set2)
print(union_set) # Output: {1, 2, 3, 4, 5}

# Intersection (finds common elements):
intersection_set = set1.intersection(set2)
print(intersection_set) # Output: {3}


# Difference (elements in set1 but not in set2):
difference_set = set1.difference(set2)
print(difference_set) # Output: {1, 2}

In [ ]:
# None
my_variable = None
print(my_variable)  # Output: None
print(type(my_variable))  # Output: <class 'NoneType'>


# Example 2: Function returning None
def my_function(x, y):
  if x > y:
    return x
  else:
    return None

result = my_function(5, 10)
print(result)  # Output: None

### NumPy Array

In [ ]:
# More efficient storage and data operations as the arrays grow larger in size than lists
# It is a Package
import numpy as np
np.__version__      # Dunder methods

'1.26.4'

In [ ]:
# Attributes of NumPy Arrays
arr = np.random.randint(0, 10, size=(3, 4))     # 3-row 4-columns array
print(type(arr))  # Output: <class 'numpy.ndarray'>
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)
print("Size:", arr.size)

# Indexing of Arrays
print("Element at (1, 2):", arr[1, 2])
print("Element at (-1, 2):", arr[-1, 2])

# Slicing of Arrays
print("First two rows:\n", arr[:2])
print("Last two columns:\n", arr[:, -2:])
print("Every other element in the first row:", arr[0, ::2])

# Reshaping of Arrays
arr_reshaped = arr.reshape(4, 3)
print("Reshaped array:\n", arr_reshaped)

<class 'numpy.ndarray'>
Shape: (3, 4)
Data type: int64
Number of dimensions: 2
Size: 12
Element at (1, 2): 6
Element at (-1, 2): 5
First two rows:
 [[2 1 0 7]
 [2 1 6 9]]
Last two columns:
 [[0 7]
 [6 9]
 [5 0]]
Every other element in the first row: [2 0]
Reshaped array:
 [[2 1 0]
 [7 2 1]
 [6 9 2]
 [7 5 0]]


In [6]:
# Joining and Splitting of Arrays
arr1 = np.random.randint(0, 5, size=(2, 3))
arr2 = np.random.randint(5, 10, size=(2, 3))

# Concatenate along rows (vertical stacking)
arr_concat_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:\n", arr_concat_rows)

# Concatenate along columns (horizontal stacking)
arr_concat_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along columns:\n", arr_concat_cols)

# Splitting the array into two equal parts along the rows
arr_split_rows = np.split(arr_concat_rows, 2, axis=0)
print("Split along rows:\n", arr_split_rows)

# Splitting the array into three equal parts along the columns
arr_split_cols = np.split(arr_concat_cols, 3, axis=1)
print("Split along columns:\n", arr_split_cols)

Concatenated along rows:
 [[4 4 0]
 [4 4 1]
 [7 8 5]
 [8 7 8]]
Concatenated along columns:
 [[4 4 0 7 8 5]
 [4 4 1 8 7 8]]
Split along rows:
 [array([[4, 4, 0],
       [4, 4, 1]]), array([[7, 8, 5],
       [8, 7, 8]])]
Split along columns:
 [array([[4, 4],
       [4, 4]]), array([[0, 7],
       [1, 8]]), array([[8, 5],
       [7, 8]])]


In [2]:
# Example showing how changing arrays of the same reference changes the original array
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = arr1  # arr2 now refers to the same array as arr1
arr2[0] = 10
print(f"arr1: {arr1}")  # Output: arr1: [10  2  3]  (arr1 is also changed)


# Example showing how copying arrays prevents changing the original
arr1 = np.array([1, 2, 3])
arr2 = arr1.copy()  # arr2 is a new copy of arr1
arr2[0] = 10
print(f"arr1: {arr1}")  # Output: arr1: [1 2 3] (arr1 remains unchanged)
print(f"arr2: {arr2}")  # Output: arr2: [10  2  3]


# Function in which .copy is used to prevent unintended changes to the original array
def modify_array_safely(original_array):
  """
  Modifies a copy of the array and returns the modified copy.
  The original array remains unchanged.
  """
  modified_array = original_array.copy()
  modified_array[0] = 100
  return modified_array


my_array = np.array([1, 2, 3])
new_array = modify_array_safely(my_array)
print(f"Original array: {my_array}")  # Output: Original array: [1 2 3]
print(f"New array: {new_array}")  # Output: New array: [100   2   3]

arr1: [10  2  3]
arr1: [1 2 3]
arr2: [10  2  3]
Original array: [1 2 3]
New array: [100   2   3]


In [3]:
# sum
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

5.62 ms ± 144 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20 μs ± 788 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
# Min, Max
np.min(big_array), np.max(big_array)

(6.611145074497671e-06, 0.9999866913836751)

In [4]:
# Aggergation Functions (all, any, argmax, argmin)
arr = np.array([1, 2, 3, 4, 5, 0])

# .any() checks if any element in the array is True
print(arr > 2)  # Output: [False False  True  True  True False] (the return is an array)
print((arr > 2).any())  # Output: True

# .all() checks if all elements in the array are True
print(arr > 0)  # Output: [ True  True  True  True  True False]
print((arr > 0).all())  # Output: False

# argmax and argmin
arr2 = np.array([1, 5, 2, 8, 3])

# argmax returns the index of the maximum element
print(np.argmax(arr2))  # Output: 3 (index of 8)

# argmin returns the index of the minimum element
print(np.argmin(arr2))  # Output: 0 (index of 1)

[False False  True  True  True False]
True
[ True  True  True  True  True False]
False
3
0


In [26]:
# Broadcasting

import numpy as np

# Case 1: Scalar and Array
# Broadcasting a scalar to an array
a = np.array([1, 2, 3])
b = 2
c = a + b  # Adds 2 to each element of 'a'
print(f"Case 1:\n{c}")

# Case 2: Array and Array (Compatible Shapes)
# Broadcasting two arrays with compatible shapes
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([1, 2, 3])  # Shape (3,)
c = a + b  # Adds 'b' to each row of 'a'
print(f"\nCase 2:\n{c}")


# Case 3: Array and Array (One Dimension with Size 1)
# Broadcasting when one dimension has size 1
a = np.array([[1], [2], [3]])  # Shape (3, 1)
b = np.array([1, 2, 3])  # Shape (3,)
c = a + b  # 'a' is expanded along the second dimension to match 'b'
print(f"\nCase 3 a shape:\n{np.shape(a)}")
print(f"\nCase 3 b shape:\n{np.shape(b)}")
print(f"\nCase 3 c array :\n{c}")
print(f"\nCase 3 c shape:\n{np.shape(c)}")
# Case 4: Error Case (Incompatible Shapes)
# Trying to broadcast incompatible shapes will raise an error
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([1, 2])  # Shape (2,)
try:
    c = a + b
except ValueError as e:
    print(f"\nCase 4 Error:\n{e}")


# Case 5:
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([10, 20, 30])  # Shape (3,)
c = a * b  # Element-wise multiplication, but often leads to errors if not intended
print(f"\nCase 5:\n{c}")


# Case 6: More Complex Broadcasting
# Demonstrating more complex broadcasting with higher dimensions
# Homework: explain how the addition is implemented.
a = np.random.randint(0, 9, (2, 3, 4))
b = np.random.randint(0, 9, (3, 1))

c = a + b  # 'b' is broadcasted along the first and third dimensions to match 'a'

print('nCase 6 \n')
print('Array a:', a, '\n')
print('Array b:', b, '\n')
print('Array c:', c, '\n')
print(f"The shapr C{c.shape}")


Case 1:
[3 4 5]

Case 2:
[[2 4 6]
 [5 7 9]]

Case 3 a shape:
(3, 1)

Case 3 b shape:
(3,)

Case 3 c array :
[[2 3 4]
 [3 4 5]
 [4 5 6]]

Case 3 c shape:
(3, 3)

Case 4 Error:
operands could not be broadcast together with shapes (2,3) (2,) 

Case 5:
[[ 10  40  90]
 [ 40 100 180]]
nCase 6 

Array a: [[[3 0 1 4]
  [6 8 8 8]
  [0 5 2 1]]

 [[5 6 4 1]
  [1 7 3 6]
  [5 3 3 5]]] 

Array b: [[6]
 [6]
 [5]] 

Array c: [[[ 9  6  7 10]
  [12 14 14 14]
  [ 5 10  7  6]]

 [[11 12 10  7]
  [ 7 13  9 12]
  [10  8  8 10]]] 

The shapr C(2, 3, 4)


In [29]:
# Assignment 1: a function to print 1 argument as a Tuple of n elements.
def my_func(var1, var2, var3):
  """
  This function accepts three variables and prints their values.
  """

  print(f"var1: {var1}, var2: {var2}, var3: {var3}")

  return var1


# Create a tuple with the parameters for the function
my_tuple = (10, "hello", True)
my_func(*my_tuple)

var1: 10, var2: hello, var3: True


10

In [ ]:
# Assignment 2: a function with a single argument as a Dictionary.
def my_func(param1, param2, param3):

  print(f"Parameter 1: {param1}, Parameter 2: {param2}, Parameter 3: {param3}")
  
  return

def my_func_1(argu_1):

  print(f"Parameter 1: {argu_1["param1"]}, Parameter 2: {argu_1["param2"]}, Parameter 3: {argu_1["param3"]}")
  
  return

my_dict = {"param1": 1, "param2": "hello", "param3": True}
my_func(**my_dict) # solution 1
my_func_1(my_dict) # solution 2

Parameter 1: 1, Parameter 2: hello, Parameter 3: True
Parameter 1: 1, Parameter 2: hello, Parameter 3: True


In [ ]:
# Assignment 3: Removing duplicates from a list using a set
my_list = [1, 2, 2, 3, 4, 4, 5, 5, 5]
unique_elements = set(my_list)
print(unique_elements) # Output: {1, 2, 3, 4, 5}

# Converting a set back to a list:
new_list = list(unique_elements)
print(new_list) # Output: [1, 2, 3, 4, 5]